name: Test base-image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: CHeckout
      uses: actions/checkout@v2
    - name: Build
      run: docker build -f Dockerfile.amd64 .
